name: "validate structure"
description: "Validate the repository structure"


runs:
  using: "composite"
  steps:
  - name: Validate Repository Structure
    shell: bash
    id: validate-structure
    run: |
      # Add your validation logic here
      # For example, check for necessary directories and files
      if [ -d "src" ] && [ -d "src/services" ]; then
        echo "Repository structure is valid"
        dir="src/services"

        # Set the suffix to check
        suffix="-service"

        # Loop through all directories in the specified directory
        for d in "$dir"/*; do
        # Check if it is a directory
          if [ -d "$d" ]; then
             # Get the directory name without the path
             dirname=${d##*/}
             # Check if the directory name ends with the specified suffix
             if [[ $dirname != *"$suffix" ]]; then
              # If it does not, print an error message and exit with a non-zero status code
              echo "Error: Directory $dirname does not have the suffix $suffix"
              exit 1
            fi
         fi
       done
      else
        echo "Repository structure is not valid"
        exit 1
      fi
