name: "validate structure"
description: "Validate the repository structure"


runs:
  using: "composite"
  steps:
  - name: Validate Repository Structure
    shell: bash
    id: validate-structure
    run: |
      # Add your validation logic here
      # For example, check for necessary directories and files
      if [ -d "src" ] && [ -d "src/services" ]; then
        echo "Repository structure is valid"
        folders=(src/services/*-service)

        if [ ${#folders[@]} -eq 0 ]; then
          echo "All service folder must have the -service suffix"
          exit 1
        else
          for folder in "${folders[@]}"; do
            if [ ! -d "$folder" ]; then
              echo "Not all the services folders in the directory have the -service suffix "
              exit 1
            fi
          done
          echo "All folders in the directory have the suffix -service"
        fi
      else
        echo "Repository structure is not valid"
        exit 1
      fi
